version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    class: 'json_log_formatter.JSONFormatter'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: "app.log"
    when: midnight
    backupCount: 7

loggers:
  uvicorn:
    handlers: [console, file]
    level: WARNING
    propagate: False

root:
  handlers: [console, file]
  level: INFO
  uvicorn:
    handlers: [ console, file ]
    level: INFO
    propagate: False